/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemUI.ServiceSeeker.ServiceSeekerUser;
import SystemModel.EcoSystem;
import SystemModel.EnterpriseManagement.Enterprise;
import SystemModel.Organization.Organization;
import SystemModel.UserAccount.UserAccount;
import SystemModel.WorkFlow.ServiceSeekerWorkReqest;
import SystemModel.WorkFlow.WorkRequest;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sudar
 */
public class ServiceSeekerUserWorkArea extends javax.swing.JPanel {
     private JPanel workArea;
    private UserAccount UserAccount;
    private Organization org;
    private Enterprise Enterprise;
    private EcoSystem ESystem;
    /**
     * Creates new form HelpSeekerUserWorkArea
     */
    public ServiceSeekerUserWorkArea(JPanel workArea,UserAccount UserAccount,Organization org,Enterprise Enterprise,EcoSystem ESystem) {
        initComponents();
        this.workArea=workArea;
        this.UserAccount=UserAccount;
        this.org=org;
        this.Enterprise=Enterprise;
        this.ESystem=ESystem;
        populateWorkQueueTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        subjectTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriptionJTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        locationTextField = new javax.swing.JTextField();
        postRequestBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.cyan);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("Service Seeker Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(329, 329, 329))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 994, -1));

        requestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Subject", "Description", "Location", "Date", "Status", "Service Provider"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 770, 150));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setText("Request :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setText("Subject : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));
        add(subjectTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 222, -1));

        descriptionJTextArea.setColumns(20);
        descriptionJTextArea.setRows(5);
        jScrollPane3.setViewportView(descriptionJTextArea);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 222, 54));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setText("Description :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setText("Location    :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));
        add(locationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 222, -1));

        postRequestBtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        postRequestBtn.setText("Post Request");
        postRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postRequestBtnActionPerformed(evt);
            }
        });
        add(postRequestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 140, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 2, 10)); // NOI18N
        jLabel5.setText("*Please input \"Funding\" as subject for Venture Capital related Help. ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    public void populateWorkQueueTable(){
         DefaultTableModel model = (DefaultTableModel) requestJTable.getModel();
        
        model.setRowCount(0);
        
        
        for (WorkRequest work : org.getWorkRequestList().getWorkRequestList()){
           if(work instanceof ServiceSeekerWorkReqest){ 
            Object[] row = new Object[10];
            row[0] = work.getSender().getEmployee().getEmpolyeeName();
            row[1] = work.getSubject();
            row[2] = ((ServiceSeekerWorkReqest) work).getDescription();
            row[3] = ((ServiceSeekerWorkReqest) work).getLocation();
            row[4] = work.getDateOfRequest();
            row[5] = work;
            row[6] = work.getReciever();
            
            model.addRow(row);
           }
        }
    }
    private void postRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postRequestBtnActionPerformed
        if(subjectTextField.getText().isEmpty() || descriptionJTextArea.getText().isEmpty() || locationTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Any of the above field(s) can't be Empty");
        }else{

            String subject = subjectTextField.getText();
            String desp = descriptionJTextArea.getText();
            String location = locationTextField.getText();

            Date d = new Date();
            SimpleDateFormat s = new SimpleDateFormat("MM/dd/YY");
            s.format(d);
            if(subject.equals("") || subject.isEmpty() && desp.equals("") || desp.isEmpty() && location.equals("")|| location.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter valid request");
                return;
            }

            ServiceSeekerWorkReqest request = new ServiceSeekerWorkReqest();
            request.setSubject(subject);
            request.setDescription(desp);
            request.setLocation(location);
            request.setStatus("Requested");
            request.setSender(UserAccount);
            request.setDateOfRequest(d);
            org.getWorkRequestList().getWorkRequestList().add(request);
            UserAccount.getWorkQueue().getWorkRequestList().add(request);
            ESystem.getWorkRequestList().getWorkRequestList().add(request);

            populateWorkQueueTable();

            subjectTextField.setText("");
            descriptionJTextArea.setText("");
            locationTextField.setText("");

        }
    }//GEN-LAST:event_postRequestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descriptionJTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JButton postRequestBtn;
    private javax.swing.JTable requestJTable;
    private javax.swing.JTextField subjectTextField;
    // End of variables declaration//GEN-END:variables
}

