/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemUI.GlobalCommunityManager;
import SystemModel.Supplier.Supplier;
import SystemModel.EcoSystem;
import SystemModel.EnterpriseManagement.Enterprise;
import SystemModel.Organization.Organization;
import SystemModel.UserAccount.UserAccount;
import SystemModel.WorkFlow.GCOSupplyWorkRequest;
import SystemModel.WorkFlow.WorkRequest;
//import com.sun.glass.events.KeyEvent;
import java.awt.event.KeyEvent;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author Karan
 */
public class SupplyRequest extends javax.swing.JPanel {
    private JPanel workArea;
    private UserAccount UserAccount;
    private Organization org;
    private Enterprise enterprise;
    private EcoSystem ESystem;
    private Supplier s;
    /**
     * Creates new form SupplyRequest
     */
    public SupplyRequest(JPanel workArea, UserAccount UserAccount, Organization org, Enterprise enterprise, EcoSystem ESystem) {
        initComponents();
        this.workArea=workArea;
        this.UserAccount=UserAccount;
        this.org=(Organization)org;
        this.enterprise=enterprise;
        this.ESystem=ESystem;
        populateSupplyTable();
    }

    public void populateSupplyTable()
    { 
      DefaultTableModel model = (DefaultTableModel) ngoReqTbl.getModel();
        
        model.setRowCount(0);
        
        
        for (WorkRequest work : ESystem.getWorkRequestList().getWorkRequestList()){
           if(work instanceof GCOSupplyWorkRequest){ 
            Object[] row = new Object[10];
            row[0] = ((GCOSupplyWorkRequest) work).getReqType();
            row[1] = ((GCOSupplyWorkRequest) work).getRequest();
            row[2] = ((GCOSupplyWorkRequest) work).getQuantity();
            row[3] = work;
            row[4] = work.getSender();
           
            
            model.addRow(row);
           }
        } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ngoReqTbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reqTxt = new javax.swing.JTextField();
        qtyTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        comboReqType = new javax.swing.JComboBox<>();
        barChartBtn = new javax.swing.JButton();
        lblCheckReq = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.cyan);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("Supply Request");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(544, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(466, 466, 466))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setText("SUPPLY REQUEST: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        ngoReqTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Type", "Requirements", "Quantity", "Status", "Source"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ngoReqTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 760, 116));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Request Type :  ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 141, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Quantity of Materials : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Requirements : ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 141, -1));

        reqTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reqTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                reqTxtKeyTyped(evt);
            }
        });
        add(reqTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 162, -1));

        qtyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyTxtKeyTyped(evt);
            }
        });
        add(qtyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 162, -1));

        submitBtn.setBackground(java.awt.Color.gray);
        submitBtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 87, 34));

        comboReqType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Technical_Lab", "Workstation_PC", "Softwares", "Empty_Labs", "Labs_Assistance" }));
        comboReqType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboReqTypeActionPerformed(evt);
            }
        });
        add(comboReqType, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 162, -1));

        barChartBtn.setBackground(java.awt.Color.gray);
        barChartBtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        barChartBtn.setText("See Supplies Bar Chart");
        barChartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barChartBtnActionPerformed(evt);
            }
        });
        add(barChartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 210, 35));
        add(lblCheckReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 330, 20));

        backBtn.setBackground(java.awt.Color.gray);
        backBtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 88, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_backBtnActionPerformed

    private void reqTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reqTxtKeyTyped
        /*char c= evt.getKeyChar();
        if(!(Character.isAlphabetic(c)) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }*/
    }//GEN-LAST:event_reqTxtKeyTyped

    private void qtyTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTxtKeyTyped
        char c= evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();}
    }//GEN-LAST:event_qtyTxtKeyTyped

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        try{
            String rType = comboReqType.getSelectedItem().toString();
            String req =   reqTxt.getText();
            int quantity = Integer.parseInt(qtyTxt.getText());
            if(rType.equals("") || rType.isEmpty() && req.equals("") || req.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Any of the above field(s) can't be empty");
                return;
            }
            
            try{
                Integer.parseInt(qtyTxt.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Quantity has to be number");    
            }

            
            GCOSupplyWorkRequest request = new GCOSupplyWorkRequest();

            request.setReqType(rType);
            request.setRequest(req);
            request.setQuantity(quantity);
            request.setStatus("Requested");
            request.setSender(UserAccount);

            org.getWorkRequestList().getWorkRequestList().add(request);
            UserAccount.getWorkQueue().getWorkRequestList().add(request);
            ESystem.getWorkRequestList().getWorkRequestList().add(request);

            populateSupplyTable();

            reqTxt.setText("");
            
            qtyTxt.setText("");  
        } 

        catch(NumberFormatException e){} 

    }//GEN-LAST:event_submitBtnActionPerformed

    private void comboReqTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboReqTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboReqTypeActionPerformed

    private void barChartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barChartBtnActionPerformed
        
        DefaultCategoryDataset d = new DefaultCategoryDataset();
        int a=0;
        int b=0;
        int c=0;
        int m=0;
        int n=0;
        for (WorkRequest work : org.getWorkRequestList().getWorkRequestList()){
            if(work instanceof GCOSupplyWorkRequest)
            {
                if(((GCOSupplyWorkRequest) work).getReqType().equals("Technical_Lab")){
                    a=a+1;
                }
                if(((GCOSupplyWorkRequest) work).getReqType().equals("Workstation_PC")){
                    b=b+1;
                }
                if(((GCOSupplyWorkRequest) work).getReqType().equals("Softwares")){
                    c=c+1;
                }
                if(((GCOSupplyWorkRequest) work).getReqType().equals("Empty_Labs")){
                    m=m+1;
                }
                if(((GCOSupplyWorkRequest) work).getReqType().equals("Labs_Assistance")){
                    n=n+1;
                }
            }
        }
        
        d.setValue(a, "Request Type","Technical_Lab");
        d.setValue(b, "Request Type","Workstation_PC");
        d.setValue(c, "Request Type","Softwares");
        d.setValue(m, "Request Type","Empty_Labs");
        d.setValue(n, "Request Type","Labs_Assistance");

        JFreeChart chart = ChartFactory.createBarChart("Request Fulfilled", "Request Type", "type", d, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.blue);
        ChartFrame f = new ChartFrame("Request Analysis",chart);
        f.setVisible(true);
        f.setSize(500,400); 

    }//GEN-LAST:event_barChartBtnActionPerformed

    private void reqTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reqTxtKeyReleased
        // TODO add your handling code here:
        
        String validReq = "^[A-Za-z0-9\\s]{1,50}$";
        Pattern pattern = Pattern.compile(validReq);
        Matcher match = pattern.matcher(reqTxt.getText());

        if (!match.matches()) {

            lblCheckReq.setText("Please Enter Valid Requirements with aplhabets and number");

        } else {

            lblCheckReq.setText(null);

        }
    }//GEN-LAST:event_reqTxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton barChartBtn;
    private javax.swing.JComboBox<String> comboReqType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCheckReq;
    private javax.swing.JTable ngoReqTbl;
    private javax.swing.JTextField qtyTxt;
    private javax.swing.JTextField reqTxt;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}

