/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemUI.Creator;
import SystemModel.EcoSystem;
import SystemModel.EnterpriseManagement.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author sudar
 */
public class CreatorAdminWorkArea extends javax.swing.JPanel {
    private JPanel workArea;
    private Enterprise enterprise;
    
    /**
     * Creates new form VolunteerAdminWorkArea
     */
    public CreatorAdminWorkArea(JPanel workArea,Enterprise enterprise) {
        initComponents();
        this.enterprise=enterprise;
        this.workArea=workArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        manageEmployeeJBtn = new javax.swing.JButton();
        manageUserAccountJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.cyan);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Creator Deck");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        manageEmployeeJBtn.setBackground(java.awt.Color.gray);
        manageEmployeeJBtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        manageEmployeeJBtn.setText("Employee");
        manageEmployeeJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJBtnActionPerformed(evt);
            }
        });
        add(manageEmployeeJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 258, 60));

        manageUserAccountJBtn.setBackground(java.awt.Color.gray);
        manageUserAccountJBtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        manageUserAccountJBtn.setText("User Account");
        manageUserAccountJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountJBtnActionPerformed(evt);
            }
        });
        add(manageUserAccountJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 258, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void manageEmployeeJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJBtnActionPerformed
        ManagementEmployee mng = new ManagementEmployee(workArea, enterprise.getOrganizationDirectory());
        workArea.add("ManageEmployee", mng);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea); 
    }//GEN-LAST:event_manageEmployeeJBtnActionPerformed

    private void manageUserAccountJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountJBtnActionPerformed
        ManagmentUserAccount mng = new ManagmentUserAccount(workArea, enterprise);
        workArea.add("ManageUserAccount", mng);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_manageUserAccountJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageEmployeeJBtn;
    private javax.swing.JButton manageUserAccountJBtn;
    // End of variables declaration//GEN-END:variables
}

